/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	ledinit(LED_GREEN_PIN);
	ledinit(LED_ORANGE_PIN);
	ledinit(LED_RED_PIN);
	ledinit(LED_BLUE_PIN);

	while(1)
	{
		ledblink(LED_GREEN_PIN, 500);
		ledblink(LED_ORANGE_PIN, 500);
		ledblink(LED_RED_PIN, 500);
		ledblink(LED_BLUE_PIN, 500);
	}
	return 0;
}
