/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"


#include "switch.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	switchinit();
	UartInit(9600);
	char ch[20];

	UartPuts("Hello world!\n");
	DelayMs(1000);
	while(1)
	{
		while(switch_extintr_flag  == 0)
				;
		switch_extintr_flag = 0;
		sprintf(ch,"count = %d\r\n",count);
		DelayMs(300);
		UartPuts(ch);
	}
	return 0;
}
